pekko.grpc.client {
  "helloworld.GreeterService" {
    host = 127.0.0.1
    port = 8080
    use-tls = false
  }
}

pekko.persistence.journal.plugin = "jdbc-journal"
pekko.persistence.snapshot-store.plugin = "jdbc-snapshot-store"

jdbc-journal {
  use-shared-db = "slick"
  tables {
    event_journal {
      table-name = "event_journal"
    }
  }
}

jdbc-snapshot-store {
  use-shared-db = "slick"
  tables {
    snapshot {
      table-name = "snapshot"
    }
  }
}

jdbc-read-journal {
  use-shared-db = "slick"
}

pekko-persistence-jdbc.shared-databases {
  slick {
    profile = "slick.jdbc.H2Profile$"
    db {
      url = "jdbc:h2:mem:grocery-store;DB_CLOSE_DELAY=-1;USER=sa;PASSWORD=;DATABASE_TO_UPPER=FALSE"
      driver = "org.h2.Driver"
      connectionPool = disabled
      keepAliveConnection = true
    }
  }
}

pekko.actor {
  serialization-bindings {
    "at.fhv.sysarch.lab2.homeautomation.external.grpc.CborSerializable" = jackson-json
  }
}

pekko.http.server.preview.enable-http2 = on